# Generated by Django 5.2.1 on 2025-06-05 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Playa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='archivos/')),
                ('playa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='Playa.playa')),
            ],
        ),
    ]
